"""Added JournalEntry model

Revision ID: 126f81ec98db
Revises: 1f92b05b77c9
Create Date: 2017-05-28 18:12:59.885673

"""

# revision identifiers, used by Alembic.
revision = '126f81ec98db'
down_revision = '1f92b05b77c9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=100), nullable=True),
    sa.Column('text', sa.UnicodeText(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('edited_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal')
    # ### end Alembic commands ###
