"""ListTask color field

Revision ID: 1f92b05b77c9
Revises: 41ae661bc0a2
Create Date: 2015-08-22 16:04:21.984212

"""

# revision identifiers, used by Alembic.
revision = '1f92b05b77c9'
down_revision = '41ae661bc0a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listtasks', sa.Column('color', sa.Unicode(length=8), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listtasks', 'color')
    ### end Alembic commands ###
