"""added Task color

Revision ID: 387975fc4c6f
Revises: 126f81ec98db
Create Date: 2017-11-08 13:59:15.650632

"""

# revision identifiers, used by Alembic.
revision = '387975fc4c6f'
down_revision = '126f81ec98db'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('color', sa.Unicode(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'color')
    # ### end Alembic commands ###
