"""change column name

Revision ID: 41ae661bc0a2
Revises: 4544bae9f982
Create Date: 2015-07-28 21:18:31.485136

"""

# revision identifiers, used by Alembic.
revision = '41ae661bc0a2'
down_revision = '4544bae9f982'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
